################################################################################
MLI_FILE		= cordova_progress.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= cordova-plugin-progress
################################################################################
